// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26621.2")]
    public partial class UIMap
    {
        
        #region Properties
        public UIApp6Window UIApp6Window
        {
            get
            {
                if ((this.mUIApp6Window == null))
                {
                    this.mUIApp6Window = new UIApp6Window();
                }
                return this.mUIApp6Window;
            }
        }
        #endregion
        
        #region Fields
        private UIApp6Window mUIApp6Window;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26621.2")]
    public class UIApp6Window : XamlWindow
    {
        
        public UIApp6Window()
        {
            #region Условия поиска
            this.SearchProperties[XamlControl.PropertyNames.Name] = "App6";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("App6");
            #endregion
        }
        
        #region Properties
        public XamlControl UIItemImage
        {
            get
            {
                if ((this.mUIItemImage == null))
                {
                    this.mUIItemImage = new XamlControl(this);
                    #region Условия поиска
                    this.mUIItemImage.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUIItemImage.SearchProperties["Instance"] = "5";
                    this.mUIItemImage.WindowTitles.Add("App6");
                    #endregion
                }
                return this.mUIItemImage;
            }
        }
        #endregion
        
        #region Fields
        private XamlControl mUIItemImage;
        #endregion
    }
}
